### PR TITLE
Add binary frameworks

### PR DESCRIPTION
**Pull request by lauracalinoiu**
Add AWSCore.framework and AWSMobileAnalytics.framework

### CODE REVIEW

**Comment by rudolf-adamkovic** [comment]
@lauracalinoiu 

> Use raws in paths

What are "raws"?

**Comment by lauracalinoiu** [comment]
@salutis, because we keep the frameworks in git and we can not download just parts of the git repository, we could use "raw" version of the file: 
[download just parts of the git repo](https://stackoverflow.com/a/4605068/4875178)

**Comment by rudolf-adamkovic** [comment]
@lauracalinoiu 

> [...] we could use "raw" version of the file: [...]

I see. What about `Link frameworks using "raw.githubusercontent.com"` instead? Makes more sense than `Use raws in paths`, IMO.

**Comment by lauracalinoiu** [comment]
@salutis, thank you for your suggestion.

**Comment by lauracalinoiu** [comment]
Speed up build PR is passing when using binaries: https://github.com/eggheadgames/acro-ios/pull/633

I ended up uploading frameworks to [Releases](https://github.com/eggheadgames/aws-sdk-ios-mobileanalytics/releases). 

Some thoughts with what I've learned:
1. We are using git for storing frameworks, maybe not the best option (but it works), because git is for versioning. 
2. With git is not easy to access individual zip files. - This is why I've used **Releases** 
3. We need to keep track with the Xcode version and Swift version under which binaries are compiled. 
4. Is it a good idea to have the same release version number for aws-sdk-ios-mobileanalytics and the official aws-sdk-ios?

After this is approved and merged, I also need to make more changes in `acro-ios` Cartfile.

**Comment by rudolf-adamkovic** [comment]
@lauracalinoiu Do we even need to merge this if the binary is in Releases and that's all we need? In other words, can Carthage use that without having anything in the repository itself?

**Comment by lauracalinoiu** [comment]
@salutis, Carthage needs the binary project specifications: AWSCore.json and AWSMobileAnalytics.json. Those tell Carthage where binaries are located. Json-s are located into the repository itself. 

At a later release, we need to update the json-s. So, I'm not sure if we need to merge.

**Comment by rudolf-adamkovic** [comment]
@lauracalinoiu 

> So, I'm not sure if we need to merge.

Well just try to use it. Plug it into an app _without_ pointing to this branch. If that works, we don't need to add those JSON files. If not, we do and this needs to be merged.

**Comment by rudolf-adamkovic** [comment]
Cleared _Reviewers_ as this is not ready for review yet. See my comment above.

**Comment by mikemee** [comment]
@lauracalinoiu 

I think @salutis is right here (again!) and the JSON files are not needed.  And, given that the build in acro has no knowledge of this branch, I think we have the proof already.

I found this: https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file which suggests that it just uses the tag for the version.  If so, I suggest we remove these JSON files and replace with change that updates the readme to explain:

1) how to use the cartfile settings to use this
2) how to build and update this when Amazon makes a new release

This is all rather weird, and to be honest, I think the "right" solution is to add the source code back and automate the build and release process using CI (e.g. using Travis as the above Carthage link describes), but in the interests of moving forward....!

**Comment by mikemee** [comment]
> given that the build in acro has no knowledge of this branch, I think we have the proof already.

Oops, I see that it is in the name!  I'll try it without that in the name...

**Comment by mikemee** [comment]
@salutis @lauracalinoiu So I tried removing the JSON dependency  by using the following in the `Cartfile`:
```
github "eggheadgames/aws-sdk-ios-mobileanalytics"
```
Then I did a `carthage bootstrap` and it updated the `Cartfile.resolved` with:
```
github "eggheadgames/aws-sdk-ios-mobileanalytics" "2.5.7"
```
and it downloaded ONLY one file: `AWSCore.framework`. So, it didn't work quite as we need...  

To move forward, we could:
 * use the JSON file method
 * set up another repo `aws-sdk-ios-core` and put the core framework file there, add a Cartfile here that specified that as a dependency, have just the mobileanalytics file here (or just include both in our `Cartfile`)

Other ideas?

**Comment by lauracalinoiu** [comment]
@mikemee, @salutis we can try out like this: https://stackoverflow.com/a/35954976/4875178
I saw this answer, but only now I understand it :). Sorry

**Comment by mikemee** [comment]
@lauracalinoiu I saw that too, but I when I tried it, I Carthage would only download one framework, not both. Perhaps you have the magic touch 🤞

**Comment by lauracalinoiu** [comment]
@mikemee, I'm trying this now. Removing the release and adding a new one ( using just `master`), so no json-s. Let's see.

**Comment by lauracalinoiu** [comment]
@mikemee, @salutis 

Locally I've used `carthage bootstrap --platform iOS --use-ssh`.

We have this on BB: `carthage bootstrap --platform ios --no-use-binaries --verbose`, my assumption is that `--no-use-binaries` does not allow for downloading our binary frameworks. 

Also, locally when I use `--no-use-binaries` flag, time to build is way to bigger than when I use no flag.

**Comment by rudolf-adamkovic** [comment]
Surely enough, all we need is to attach the framework to a GitHub release:

> Carthage can automatically use prebuilt frameworks, instead of building from scratch, if they are attached to a GitHub Release on your project’s repository **or** via a binary project definition file.

No need for the binary project definition file. If we didn't use GitHub, we would have to do that. But we use it, so that's good.

Next actions:

* @lauracalinoiu — Please, close this pull request and open a new one for adding instructions about how to build the framework. When creating a new branch, please do not add the `feature/` prefix. We don't do that anymore, we will add new `CONTRIBUTING.md` soon.. Also, be sure to link this pull request from the new one, so that the future ourselves will know what happened.
* @mikemee  — Please, create a new `aws-sdk-ios-core` repository for the core framework.
* @lauracalinoiu  — Please, repackage `aws-sdk-ios-mobileanalytics.framework.zip` to include only the `AWSMobileAnalytics.framework` framework. The other one will go into its own repository.

P.S.

> This is all rather weird, and to be honest, I think the "right" solution is to add the source code back and automate the build and release process using CI [...]

I disagree. The thing barely builds. With warnings, static analyzer errors and tests don't work. Waste of time and not our business.

**Comment by mikemee** [comment]
> @mikemee — Please, create a new aws-sdk-ios-core repository for the core framework.

Done.

**Comment by mikemee** [comment]
> Please, repackage aws-sdk-ios-mobileanalytics.framework.zip to include only the AWSMobileAnalytics.framework framework

@lauracalinoiu - I did this in a really simple (stupid!) way. I just downloaded the other zip file and deleted the MobileAnalytics folder. This didn't work, as discussed here:

https://github.com/eggheadgames/aws-sdk-ios-core/issues/1

I also tried to do the same for the release in this folder and broke it the same way

I look forward to reading your README on how to do this properly!  👍

**Comment by lauracalinoiu** [comment]
@mikemee, @salutis 

We do not need a second project  `aws-sdk-ios-core`.

Here are my steps: 

1. release on `aws-sdk-ios-mobileanalytics`, that contains `aws-sdk-ios-mobileanalytics.framework.zip`. The structure of the zip is: 

Carthage/Build/iOS/AWSMobileAnalytics.framework 
Carthage/Build/iOS/AWSCore.framework

2. `acro-ios`, Cartfile with this entry: `github "eggheadgames/aws-sdk-ios-mobileanalytics"`

3. for `acro-ios`, perform: `carthage update aws-sdk-ios-mobileanalytics --platform iOS`, to obtain an updated `Cartfile.resolved`

4. commit `Cartfile.resolved` (I have pushed this one)

5. Carthage bootstrap: 

   a) locally: `carthage bootstrap --platform iOS --use-ssh` -> I can see both AWSMobileAnalytics.framework and AWSCore.framework in Carthage folder. 

   b) on Buddy Build: - compilation error: AWSMobileAnalytics not found, because BB uses `--no-use-binaries`

screen shot 2017-06-01 at 10 59 24 png unknown today at 11 12 41



Locally, both frameworks are downloaded using just `aws-sdk-ios-mobileanalytics`. 
What can we do with `--no-use-binaries` from Buddy Build? 

If I use the `--no-use-binaries` flag locally, both frameworks are not downloaded.

**Comment by lauracalinoiu** [comment]
@mikemee, I am trying to reproduce what happened that Carthage downloaded only one framework.

**Comment by rudolf-adamkovic** [comment]
@lauracalinoiu Great find that it downloads both frameworks! As for `--no-use-binaries`, why not simply follow the advice that's in the screenshot you posted? 😄 

> Using the buddybuild predefined Carthage command line.
> To specify a different Carthage command line, visit http://docs.buddybuild.com/docs/carthage
> Using Command Line: `carthage bootstrap --platform ios --no-use-binaries --verbose`

Check out [Running a custom Carthage command](http://docs.buddybuild.com/docs/carthage#running-a-custom-carthage-command), it's simple.

@mikemee Please go ahead and delete the `aws-sdk-ios-core` repository. 🤡

**Comment by lauracalinoiu** [comment]
@salutis, thank you that you looked into this. :) 
I am reading the advice.

**Comment by lauracalinoiu** [comment]
@mikemee, @salutis 
https://github.com/eggheadgames/acro-ios/pull/633 build was a success. 
I am closing this.

**Comment by rudolf-adamkovic** [comment]
@lauracalinoiu Created #6 to update `README.md`.

**Comment by lauracalinoiu** [comment]
@salutis, Thank you. I am writing it now.

**Comment by mikemee** [comment]
> Check out Running a custom Carthage command, it's simple.

@salutis 

Do we really want to go here?  Everything custom we do for BB is something that won't get automagically improved when BB does updates.

Otoh, if `--no-use-binaries` was not bringing down the framework either singly or both, then I guess we have no choice and may as well use one repo....

**Comment by rudolf-adamkovic** [comment]
@mikemee 

> Do we really want to go here?  Everything custom we do for BB is something that won't get automagically improved when BB does updates.

We do and we're there already. 😄 

> Otoh, if `--no-use-binaries` was not bringing down the framework either singly or both, then I guess we have no choice and may as well use one repo....

I don't understand this part at all.

**Pull request closed without merging**
