### PR TITLE
Add AWSCore and AWSMobileAnalytics

### PR DESCRIPTION
**Pull request by lauracalinoiu**

### CODE REVIEW

**Comment by rudolf-adamkovic** [comment]
In review.

**Review by rudolf-adamkovic — CHANGES_REQUESTED** [review]
Suggested changes:

* Remove _Deployment Target_ for `AWSCore`, we want to inherit from `AWSAnalytics`
* Remove _Deployment Target_ for `AWSMobileAnalytics`, we want to inherit from `AWSAnalytics`
* There are 10 markdown files with "no rule to process file":
    ```
    warning: no rule to process file '/Users/Salutis/Documents/Egghead Games/aws-sdk-ios-mobileanalytics/AWSCore/FMDB/README.markdown' of type net.daringfireball.markdown for architecture x86_64
    warning: no rule to process file '/Users/Salutis/Documents/Egghead Games/aws-sdk-ios-mobileanalytics/AWSCore/GZIP/LICENCE.md' of type net.daringfireball.markdown for architecture x86_64
    warning: no rule to process file '/Users/Salutis/Documents/Egghead Games/aws-sdk-ios-mobileanalytics/AWSCore/GZIP/README.md' of type net.daringfireball.markdown for architecture x86_64
    warning: no rule to process file '/Users/Salutis/Documents/Egghead Games/aws-sdk-ios-mobileanalytics/AWSCore/Mantle/LICENSE.md' of type net.daringfireball.markdown for architecture x86_64
    warning: no rule to process file '/Users/Salutis/Documents/Egghead Games/aws-sdk-ios-mobileanalytics/AWSCore/Mantle/README.md' of type net.daringfireball.markdown for architecture x86_64
    warning: no rule to process file '/Users/Salutis/Documents/Egghead Games/aws-sdk-ios-mobileanalytics/AWSCore/Reachability/README.md' of type net.daringfireball.markdown for architecture x86_64
    warning: no rule to process file '/Users/Salutis/Documents/Egghead Games/aws-sdk-ios-mobileanalytics/AWSCore/TMCache/README.md' of type net.daringfireball.markdown for architecture x86_64
    warning: no rule to process file '/Users/Salutis/Documents/Egghead Games/aws-sdk-ios-mobileanalytics/AWSCore/UICKeyChainStore/README.md' of type net.daringfireball.markdown for architecture x86_64
    warning: no rule to process file '/Users/Salutis/Documents/Egghead Games/aws-sdk-ios-mobileanalytics/AWSCore/XMLDictionary/LICENCE.md' of type net.daringfireball.markdown for architecture x86_64
    warning: no rule to process file '/Users/Salutis/Documents/Egghead Games/aws-sdk-ios-mobileanalytics/AWSCore/XMLDictionary/README.md' of type net.daringfireball.markdown for architecture x86_64
    ```
* Treat compiler warnings as errors for _Release_ builds
* Add unit tests

BTW, static analyzer reports 11 issues - memory leaks, API misuse, logic errors, etc.

**Comment by mikemee** [comment]
@salutis 

> BTW, static analyzer reports 11 issues - memory leaks, API misuse, logic errors, etc.

I don't think we want to fix those....   In which case....

> Treat warnings as errors for Release builds

... should we leave those alone?

**Comment by rudolf-adamkovic** [comment]
@mikemee 

> ... should we leave those alone?

No, those are static analyzer errors. Compiler warnings and errors are a different thing.

**Comment by rudolf-adamkovic** [comment]
Edit: Added "Add unit tests" suggestion

**Comment by mikemee** [comment]
@salutis 

> Add unit tests

Please no.  This is just intended to fix the long Carthage build time, not to create a fully supported component that we own. Let's do the minimal amount that makes sense. It's not our code. I don't want to start messing with it or adding tests around it. We're not going to make any changes to the code based on test results anyway.  

Can we just ship this after correcting the framework / Xcode packaging issues you've found above (thanks!)?  We'll put the effort into removing this dependency instead of putting lipstick on it.

**Comment by mikemee** [comment]
@salutis I think this is ready for you again (right @lauracalinoiu ?)

**Comment by lauracalinoiu** [comment]
@mikemee, not ready yet. I don't know why https://github.com/eggheadgames/acro-ios/pull/633 is failing.

**Comment by mikemee** [comment]
@lauracalinoiu Did "Treat warnings as errors for Release" cause failures because of the documentation mismatches?

**Comment by lauracalinoiu** [comment]
@mikemee, yes. Because we treat warnings as errors in release, the build is crashing. I have 2 commits that fixes documentation, but this is crazy. At a next release maybe we need to fix something more. :) This one was simple. I am waiting for BB now. Carthage is building with success locally.

**Comment by mikemee** [comment]
Ok. Yes @salutis and I chatted about this and are not yet in agreement :). But if it all builds after this, that's good.

**Comment by lauracalinoiu** [comment]
@mikemee, @salutis,
I need a review again. Thanks

**Comment by rudolf-adamkovic** [comment]
In review.

**Review by rudolf-adamkovic — CHANGES_REQUESTED** [review]
Getting there. Suggested changes:

* Set _Treat Warnings as Errors_ on `ASWAnalytics` and inherit it on both `AWSCore` and `AWSMobileAnalytics`. This applies to **all** project-wise build settings we customized.
* Add unit tests from `aws-sdk-ios`.
* Link the original source code from`README` so that we know what this thing actually is.
* Add `LICENSE`, `LICENSE.AMAZON` and `LICENSE.APACHE` from from `aws-sdk-ios` to comply with law.

**Comment by lauracalinoiu** [comment]
@salutis, @mikemee I am working on it. 
@salutis Thank you, for your great review. As always. This puts me on the track.

**Review by mikemee — CHANGES_REQUESTED** [review]
@lauracalinoiu Can you please copy over the relevant test folders from the main AWS repo and add them to a test target here and see if they run ok?

If they do, then please configure BuddyBuild to also run them?

@salutis has convinced me it's at least worth trying and it might "just work".

If it doesn't work easily, then please estimate the effort required to get the tests working but don't start. Thanks!

**Comment by mikemee** [comment]
@lauracalinoiu Also, can you please fork the amazon repo and then make the two code/documentation changes you had to fix to avoid the compile problems, and then create a PR back to the Amazon repo?  That way, hopefully, when we incorporate an update from them, we won't need to make those same changes again.

**Comment by lauracalinoiu** [comment]
Here is what I've learned when including tests:
1. Some tests rely on a `credentials.json` file. In `aws-sdk-ios` this one is git ignored. 

a) I've tried out with a valid account - 3 tests failed - I suspect that identityPool was not set. 
b) with a fake account - more tests fail ( because no credit card is set)

If we want the tests to run on BB, we need a valid credentials.json file, but there will be a security issue, to have this one available on github. 

What would be a good approach to this? 

There are also warnings in tests.

**Comment by mikemee** [comment]
@lauracalinoiu Wow, that's a lot of progress, congrats!

@salutis I have BB configured to run this branch and run the tests, and it shows the failures @lauracalinoiu mentions above.

@lauracalinoiu Where did the credentials in [`credentials.json`](https://github.com/eggheadgames/aws-sdk-ios-mobileanalytics/blob/c5feacf8ab5838a3936fbfdb4158f694ac30f224/AWSCoreTests/Resources/credentials.json) come from?  If I can find a way to add a private set to BuddyBuild, do you know how to specify the IdentityPool?

Meanwhile, we're sliding down the slope of "lots of work to get a 3rd party library going..."

**Comment by rudolf-adamkovic** [comment]
Checking...

**Comment by lauracalinoiu** [comment]
@salutis, I want to push -f, new credentials and setup.

**Comment by rudolf-adamkovic** [comment]
All right, these are not unit tests. It's a mix of unit, integration and acceptance tests. Some of them fail, some of them hang forever, some of them pass. This is a no go.

So, it looks we're headed in a wrong direction.  In other words, this is a waste of time. On the other hand, I really want this to be done properly. Here's what we will do — instead of adding sources and tests into this repository, let's just add a compiled framework instead.

From [Carthage documentation](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md):

> Dependencies that are only available as compiled binary `.framework`s are specified with the `binary` keyword and an https address that returns a binary project specification:
>
>```
>binary "https://my.domain.com/release/MyFramework.json"
>```

... and ...

> For dependencies that do not have source code available, a binary project specification can be used to list the locations and versions of compiled frameworks.  This data **must** be available via `https` and could be served from a static file or dynamically.
>
> * The JSON structure is a top-level dictionary with the key-value pairs of version / location.
> * The version **must** be a semantic version.  Git branches, tags and commits are not valid.
> * The location **must** be an `https` url.
> 
> #### Example binary project specification
>
>```
>{
>	"1.0": "https://my.domain.com/release/1.0.0/framework.zip",
>	"1.0.1": "https://my.domain.com/release/1.0.1/framework.zip"
>}
>```

**Comment by mikemee** [comment]
@lauracalinoiu Can we close this, now that you have a new PR #4  ?

**Comment by lauracalinoiu** [comment]
@mikemee, I waited for your approval. If I have it, I can close this.

**Comment by rudolf-adamkovic** [comment]
@lauracalinoiu Don't forget to delete the branch. 🌲

**Comment by mikemee** [comment]
Thanks!  We'll get there!

@lauracalinoiu

**Comment by lauracalinoiu** [comment]
@salutis, @mikemee I know that the branch had to be deleted, but I'm way too attached to it :(.

**Pull request closed without merging**
