### PR TITLE
Update README.md with instructions on build

### LINKED ISSUE #6: Document how to build iOS frameworks for Carthage
As discussed in #4:

Add instructions to `README.md` about how to build these frameworks.

### PR DESCRIPTION
**Pull request by lauracalinoiu**
will close #6 

As discussed in #4 - this PR contains instructions for building AWSMobileAnalytics.framework and AWSCore.framework.

### CODE REVIEW

**Review by rudolf-adamkovic — CHANGES_REQUESTED** [review]
I tried to follow your instructions. Here:

> 1. Prepare a release of this project 

I guess by "prepare a release" you mean "draft a new release". Let's be consistent and use the same vocabulary as GitHub uses.

> 2. Release contains aws-sdk-ios-mobileanalytics.framework.zip

The `aws-sdk-ios-mobileanalytics.framework.zip` filename needs to be enclosed in back-ticks. More importantly, I exactly followed instructions and now I'm stuck. This step says "Release contains". That is not actionable and I have no idea what to do next. As you can see, there is no `zip` file to be seen:

screen shot 2017-06-01 at 12 10 25

**Comment by lauracalinoiu** [comment]
@salutis, thanks. I am thinking of ways to improve it.

**Comment by lauracalinoiu** [comment]
@salutis @mikemee Please check if README.md is readable and easy to understand.

**Comment by rudolf-adamkovic** [comment]
In review.

**Review by rudolf-adamkovic — APPROVED** [review]
This is good to go. I do some quick readability improvements in a separate pull request.

**Comment by lauracalinoiu** [comment]
@salutis, thank you

**Pull request merged**
